apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-argocd
    tag: argocd
  name: hello-argocd-svc
  namespace: hello-argocd
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-argocd
    tag: argocd
  type: ClusterIP
